[workspace]
resolver = "2"
members = ["lla", "lla_plugin_interface", "lla_plugin_utils"]

[workspace.package]
description = "Blazing Fast and highly customizable ls Replacement with Superpowers"
authors = ["Achaq <hi@achaq.dev>"]
version = "0.3.10"
categories = ["utilities", "file-system", "cli", "file-management"]
edition = "2021"
license = "MIT"
keywords = ["ls", "file-system", "cli", "file-management"]
repository = "https://github.com/chaqchase/lla"

[workspace.dependencies]
clap = "3.2.25"
clap_complete = "3.2.5"
serde = { version = "1.0.207", features = ["derive"] }
toml = "0.8.19"
dirs = "5.0.1"
colored = "2.0"
rayon = "1.5"
chrono = "0.4"
libloading = "0.8.5"
serde_json = "1.0"
walkdir = "2.5"
tempfile = "3.2"
users = "0.11"
lla_plugin_interface = { path = "lla_plugin_interface" }
dashmap = "5.5.3"
parking_lot = "0.12"
once_cell = "1.18"
unicode-width = "0.1.11"
strip-ansi-escapes = "0.1.1"
terminal_size = "0.4.1"
dialoguer = "0.11.0"
atty = "0.2.14"
indicatif = "0.17.9"
console = "0.15.8"
regex = "1.5"
glob = "0.3"
# Protobuf dependencies
prost = "0.12"
prost-build = "0.12"

[profile.release]
lto = true
codegen-units = 1
strip = true

[profile.dev.build-override]
opt-level = 3
